name: Docker CI

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/docker.yml
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/docker.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: cache-nginx-openresty
        id: cache-nginx-openresty
        uses: actions/cache@v3
        with:
          path: openresty
          key: cache-nginx-openresty-${{ secrets.CACHE_ID }}

      - name: patch nginx-openresty
        if: steps.cache-nginx-openresty.outputs.cache-hit != 'true'
        run: | 
         export DEBIAN_FRONTEND=noninteractive
         sudo apt -o DPkg::Options::="--force-confnew" install -y dos2unix
         git clone --recursive https://github.com/SanCraftDev/openresty-quic src
         cd src
         make -j "$(nproc)"
         cd ..
         rm src/openresty-*.tar.gz
         mv src/openresty-* openresty
         rm -rf src

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=-1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ github.token }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ secrets.CACHE_ID }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ secrets.CACHE_ID }}-

      - name: Build
        uses: docker/build-push-action@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64 #,linux/amd64/v2,linux/amd64/v3 #linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6
          push: true
          tags: | 
           ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.ref_name }}
           ghcr.io/${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.ref_name }}
          build-args: |
           "BUILD=${{ github.event.repository.name }}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: show version
        if: ${{ github.event_name != 'pull_request' }}
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.ref_name }} -V

      - name: Set PR-Number (PR)
        if: ${{ github.event_name == 'pull_request' }}
        id: pr
        run: echo "::set-output name=pr::$(echo pr-${{ github.ref_name }} | sed "s/refs\/pull\/://g" | sed "s/\/merge//g")"

      - name: Build (PR)
        uses: docker/build-push-action@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64 #,linux/amd64/v2,linux/amd64/v3 #linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6
          push: true
          tags: | 
           ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ steps.pr.outputs.pr }}
           ghcr.io/${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ steps.pr.outputs.pr }}
          build-args: |
           "BUILD=${{ github.event.repository.name }}"

      - name: show version (PR)
        if: ${{ github.event_name == 'pull_request' }}
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ steps.pr.outputs.pr }} -V
